version: '3.8'

services:
  backend:
    build:
      context: ./TechAssignment/TechAssignment  # Path to backend Dockerfile
    ports:
      - "5000:80"  # API endpoint
      - "5001:5001"  # SignalR communication
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - JWT_SECRET=Your_Secret_Key
    volumes:
      - logs:/app/Logs  # Persist logs outside the container
    networks:
      - app-network

  frontend:
    build:
      context: ./employee-register-client  # Path to frontend Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:5000  # Use service name instead of localhost
      - REACT_APP_SIGNALR_URL=http://backend:5001/employeehub
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  logs:
